# Site settings
title: James Kent
description: My own personal website!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: James Kent
user_description: I work with Dr. Michelle Voss to automate processing in the lab and ask questions about the impact of aging on cognitive control.
user_title: Graduate Student
email: james-kent@uiowa.edu
twitter_username: SudoNeuroSci
github_username: jdkent

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
